### ISSUE TITLE
Create a better looking logo for Vueflare

### ISSUE THREAD

**Issue by valentinvieriu** [vueflare/website#1]
We would like to have a better looking logo for our project. The logo we have chosen we feel it represents the core idea ( a flare, and it has some of the Vuejs colors ( see [website](https://vuejs.org/) )  but somehow it feels unfinished.

We need the overview and eye of a designer to improve the finished look of our logo.

See: [CurrentLogo](https://github.com/vueflare/website/blob/master/src/.vuepress/public/logo.svg)
![ICurrentLogot](https://raw.githubusercontent.com/vueflare/website/master/src/.vuepress/public/logo.svg)

Requirements to be considered:
- We would like to use the Vue color palette - it does not need to be 1 to 1 but to feel familiar
- We would like to get some visual inspiration from 

Examples that can be used as guidance 
- [flareact](https://flareact.com/) this a is project that aims to do exactly the same as us, but using React
- [1.1.1.1](https://1.1.1.1/) - this is the new design language from Cloudflare. This is something we would love to capture in our logo

We take copyright very seriously, please propose logos created by you, or if they are free to use, provide a link to the license.

**Comment by Ruth-ikegah** [comment]
Hi @valentinvieriu I think you should add a design label to this issue so designers willing to contribute can find it easily

**Comment by MDShields7** [comment]
I just wonder if there is something you don't like about your current logo @valentinvieriu. Maybe that might give designers a bit of direction of what you are looking for.

**Comment by valentinvieriu** [comment]
@MDShields7 Fair point, let me add some more descriptive items

**Comment by royquilor** [comment]
Hi, I might be too late, but wonder if you're still taking ideas?

**Comment by DevrajDC** [comment]
[VueFlare.zip](https://github.com/vueflare/website/files/5312530/VueFlare.zip)
I have made 4 designs Please Check it Out, you can use whichever design you liked.

**Comment by valentinvieriu** [comment]
> Hi, I might be too late, but wonder if you're still taking ideas?

Yes. The issue is still open. Please submit a pull request.

Thank you

**Comment by valentinvieriu** [comment]
> [VueFlare.zip](https://github.com/vueflare/website/files/5312530/VueFlare.zip)
> 
> I have made 4 designs Please Check it Out, you can use whichever design you liked. 

That's not usually how it works. You create a pull request where you replace the existing file with your proposal. 
If you have 4 proposals you can submit 4 pull requests. You will get a preview link for all of them and people can review and vote

Can you try to do that?

**Comment by royquilor** [comment]
Thanks, I followed the starter video on hacktoberfest and did a fork, then clone locally. Did a commit, then push, but I don't think this is the correct way?


> > [VueFlare.zip](https://github.com/vueflare/website/files/5312530/VueFlare.zip)
> > I have made 4 designs Please Check it Out, you can use whichever design you liked.
> 
> That's not usually how it works. You create a pull request where you replace the existing file with your proposal.
> If you have 4 proposals you can submit 4 pull requests. You will get a preview link for all of them and people can review and vote
> 
> Can you try to do that?

**Comment by royquilor** [comment]
> > > Hi, I might be too late, but wonder if you're still taking ideas?
> > 
> > 
> > Yes. The issue is still open. Please submit a pull request.
> > Thank you
> 
> Thanks, I followed the starter video on hacktoberfest and did a fork, then clone locally. Did a commit, then push, but I don't think this is the correct way?

I figured it out ;)
